import glob
from music21 import converter, instrument, note, chord, stream
import numpy
import numpy as np
from keras.utils import to_categorical
from keras.layers import Dense, Dropout, LSTM, Activation, Reshape
from keras.models import Sequential

notes = []
durations = []
for file in glob.glob("midi/*.mid")[:5]:
    print(file)
    midi = converter.parse(file)
    notes_to_parse = None
    parts = instrument.partitionByInstrument(midi)
    if parts: # file has instrument parts
        notes_to_parse = parts.parts[0].recurse()
    else: # file has notes in a flat structure
        notes_to_parse = midi.flat.notes
    for element in notes_to_parse:
        if isinstance(element, note.Note):
            notes.append(str(element.pitch))
            durations.append(str(element.duration.type))
        elif isinstance(element, chord.Chord):
            notes.append('.'.join(str(n) for n in element.normalOrder))
            durations.append(element.duration.type)

# notes = notes[:len(notes) // 10]
sequence_length = 100
# get all pitch names
pitchnames = sorted(set(item for item in notes))
durationnames = sorted(set(item for item in durations))
# create a dictionary to map pitches to integers
note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
duration_to_int = dict((duration, number) for number, duration in enumerate(durationnames))
network_input = []
network_output = []
# create input sequences and the corresponding outputs
for i in range(0, len(notes) - sequence_length, 1):
    sequence_in = list(zip(notes[i:i + sequence_length], durations[i:i+sequence_length]))
    sequence_out = list(zip(notes[i + sequence_length: i + 2 * sequence_length], 
                            durations[i + sequence_length: i + 2 * sequence_length]))
    if len(sequence_in) == len(sequence_out):
        network_input.append([(note_to_int[char], duration_to_int[duration]) for char, duration in sequence_in])
        network_output.append([(note_to_int[char], duration_to_int[duration]) for char, duration in sequence_out])
n_patterns = len(network_input)
# reshape the input into a format compatible with LSTM layers
network_output = np.array(network_output)
network_input = numpy.reshape(network_input, (n_patterns, sequence_length, 2))
# normalize input
n_vocab = max(network_input[:, :, 0].max(), network_output[:, :, 0].max()) + 1
network_input = to_categorical(network_input)
network_output = to_categorical(network_output)

model = Sequential()
model.add(Reshape((network_input.shape[1] * network_input.shape[2], network_input.shape[3])))
model.add(LSTM(256,
#     input_shape=(network_input.shape[1], network_input.shape[2]),
    return_sequences=True
))
model.add(Dropout(0.3))
model.add(LSTM(512, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(256))
model.add(Dense(256))
model.add(Dropout(0.3))
model.add(Dense(2*n_vocab * sequence_length))
model.add(Reshape((sequence_length, 2, n_vocab)))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

# model.summary()


from keras.callbacks import ModelCheckpoint
# model.load_weights('model.h5')
model.fit(network_input, network_output, epochs=10, callbacks=[ModelCheckpoint('model.h5')])

start = numpy.random.randint(0, len(network_input)-1)
int_to_note = dict((number, note) for number, note in enumerate(pitchnames))
int_to_duration = dict((number, duration) for number, duration in enumerate(durationnames))
pattern = network_input[start]
prediction_output = []
# generate 500 notes
for note_index in range(5):
    prediction_input = pattern.reshape(1, sequence_length, 2, n_vocab)
#     prediction_input = numpy.reshape(pattern, (1, len(pattern), 1))
    prediction_input = prediction_input / float(n_vocab)
    predictions = model.predict(prediction_input, verbose=0)[0]
    for prediction in predictions:
        index = numpy.argmax(prediction[0])
        duration_i = numpy.argmax(prediction[1])
        result = int_to_note[index]
        duration = int_to_duration[duration_i]
        prediction_output.append((result, duration))
        result = np.zeros_like(prediction)
        result[0][index] = 1
        result[1][duration_i] = 1
        pattern = np.concatenate([pattern, [result]])
    pattern = pattern[len(pattern) - sequence_length:len(pattern)]

offset = 0
output_notes = []
# create note and chord objects based on the values generated by the model
for pattern, duration in prediction_output:
    # pattern is a chord
    if ('.' in pattern) or pattern.isdigit():
        notes_in_chord = pattern.split('.')
        notes = []
        for current_note in notes_in_chord:
            new_note = note.Note(int(current_note))
            new_note.duration = duration
            new_note.storedInstrument = instrument.Accordion()
            notes.append(new_note)
        new_chord = chord.Chord(notes)
        new_chord.offset = offset
        output_notes.append(new_chord)
    # pattern is a note
    else:
        new_note = note.Note(pattern)
        new_note.offset = offset
        new_note.storedInstrument = instrument.Accordion()
        output_notes.append(new_note)
    # increase offset each iteration so that notes do not stack
    offset += 0.5

midi_stream = stream.Stream(output_notes)
midi_stream.write('midi', fp='test_output3.mid')
